#! /bin/sh

# Autostart
/usr/bin/dunst &
sxhkd &
picom &
polybar top &
feh --bg-fill ~/Desktop/Media/Wallpapers/ms11holidaywpaper.jpg &
discord &
imwheel &
flameshot &
wmname LG3D &

bspc monitor -d I II III IV V 
bspc config border_width        0 
bspc config window_gap          6 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config normal_border_color  "#2e3440"
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


