#! /bin/sh

# Autostart
# Uncomment below line if you have dunst installed
# /usr/bin/dunst &
# Uncomment below line if you have sxhkd installed
# sxhkd &
# Uncomment below line if you have picom installed
# picom &
# Uncomment below line if you have polybar installed
# polybar top &
# Instructions on installing feh can be found here => https://feh.finalrewind.org/.
# Uncomment below line if you have feh installed
# feh --bg-fill path/to/your/wallpaper &
# Optional - discord
# discord &
# Optional -imwheel
# imwheel &
# Optional
# flameshot &
# Optional - I have this so I can run some Java programs properly
# wmname LG3D &

bspc monitor -d I II III IV V 
bspc config border_width        0 
bspc config window_gap          6 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config normal_border_color  "#2e3440"
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


